# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool: test-agent

variables:
  workingDirectory: '$(System.DefaultWorkingDirectory)/Environment/UAT'

stages:
 - stage:
   jobs:
   - job:
     steps:
      - task: CmdLine@2
        displayName: Terraform Init
        inputs:
         script: |
          terraform init
         workingDirectory: $(workingDirectory)
      - task: CmdLine@2
        displayName: terraform validate
        inputs:
          script: |
            terraform validate 
          workingDirectory: $(workingDirectory)

# plan stage
 - stage:
   jobs:
   - job:
     steps:
     - task: CmdLine@2
       displayName: terraform plan 
       inputs:
         script: |
           terraform plan 
         workingDirectory: $(workingDirectory)
         
