trigger:
 - main
pool: test-agentv


variables:
  workingDirectory: '$(System.DefaultWorkingDirectory)/Environment/UAT'

stages:
 - stage: validation
   jobs:
   - job: init
     steps: 
      - task: CmdLine@2
        inputs:
          script: |
            terraform init
          workingDirectory: $(workingDirectory)