trigger:
  #branches: 
   # exclude:
    #- main
pool: 
  name: test-agentv

variables:
  workingDirectory: '$(System.DefaultWorkingDirectory)/Environment/UAT'

stages:
 - stage: validation
   jobs:
    - job: init
      steps:
       - task: Run terraform init 
         inputs: terraform init